language: python
  
script:
- echo "skipping tests"

install:
    - nvm install 8.9
    - npm install yarn
    - yarn global add  firebase-tools
    - yarn install
    
script:
    - echo "skipping tests"
    - yarn build
    - firebase use --token $firebase_key production
    - python getInstaImages.py
    - cat instaimages.json
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token "$FIREBASE_TOKEN"
