language: node_js
deploy:
  provider: firebase
  token:
    secure: YOUR ENCRYPTED token
env:
  global:
    secure: qr0p/izDRd+tNJh94hT08zX3aeDFTTT+qZzqIabjoJ0Twfgkdlq8cBeSyvrGwphacqG4wNP31BNhSI+A2x38bY0jP+LtdHLejdElzrCqzqt2DIwC8JvhRaVbDPwIUbFYKk0kokIlvFZ346IvzWARy4fE3qx0i51XKqGsPjXV8UF3cIt5WykWzVfoL6t3vLmkZU8hk9GnohsmlUaI5wSuOAUE5U5r3JQKAIDW1IrGFChviHtGXwj7V3eXRz+dAsKtiAjNnknMzqC9CIRyzxa4QL1KpCb7VRqzjHLfn2BEJ+TvGpCADphbg+bDQEFkj5FSybV28gBrahGIVABWbBcNvUu3Ly3Sd/Cj0dqMJaHQvuELqMSrpkkJg1e8kjnoxA1EY5XUcMf8jTdD7gv5Uwb4voOdVN7JZqTjue5NlLMkR4YiCryQZFWZkV03xeVFC4KAzEMRViWKSJH9rV08pWCc3LMbfGwah//2sjPYh47p44rNxmyPVnShvwdX7sZtXHBBJUlmZIfNgD1wV6BHy46R4FdIV2iL/CB6f9NNcBHCByH5V3zP3aE/pSAVtVlnsQL+/oi+1XweeI1fqVAxQMMmbX4NmDGszp/3b12z4lr5AI5MYfZGBiuimENHKtFR96AQcoxt2y+WhiN7kO3eo/fgTrSBRPC/L10p0LJlIzDqWC0=
