language: node_js
node_js:
  - "8" 
  
script:
- echo "skipping tests"

install:
    - yarn global add  firebase-tools
    - yarn install
    
script:
    - yarn build
    - firebase use --token $firebase_key production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token "$FIREBASE_TOKEN"
